name             'vagrant-consul-cluster'
maintainer       'The Authors'
maintainer_email 'you@example.com'
license          'all_rights'
description      'Installs/Configures vagrant-consul-cluster'
long_description 'Installs/Configures vagrant-consul-cluster'
version          '0.1.0'

depends 'apt'
depends 'consul-cluster'
