name             'vagrant-consul-cluster'
maintainer       'Adam Krone'
maintainer_email 'adam.krone@thirdwavellc.com'
license          'Apache v2.0'
description      'Installs/Configures vagrant-consul-cluster'
long_description 'Installs/Configures vagrant-consul-cluster'
version          '0.1.0'

depends 'apt'
depends 'consul-cluster'
